# Generated by Django 5.1.6 on 2025-05-11 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_gameroom_chatmessage_player'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='player',
            name='last_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='game_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='base.gameroom'),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='current_question_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='difficulty',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='question_count',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='quiz_data',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='topic',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='avatar_url',
            field=models.URLField(default='https://api.dicebear.com/7.x/avataaars/svg?seed=default'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('user', 'game_room')},
        ),
    ]
