# Generated by Django 5.1.6 on 2025-05-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_gamesession_player_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='current_question',
            field=models.IntegerField(default=0),
        ),
    ]
