# Generated by Django 5.1.6 on 2025-05-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_gamesession_current_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='answers_state',
            field=models.JSONField(default=dict),
        ),
    ]
