# Generated by Django 5.1.6 on 2025-05-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_chatmessage_options_player_last_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='last_answer',
            new_name='selected_answer',
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='quiz_data',
            field=models.JSONField(),
        ),
    ]
