# Generated by Django 5.1.6 on 2025-05-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_gamesession_answers_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
