# Generated by Django 5.1.6 on 2025-05-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_gamesession_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='question_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
