# Generated by Django 5.1.6 on 2025-05-05 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_gamesession_question_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesession',
            old_name='timer',
            new_name='question_timer',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='answers_state',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='started',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting for players'), ('STARTING', 'Game starting'), ('IN_PROGRESS', 'Game in progress'), ('SHOWING_LEADERBOARD', 'Showing leaderboard'), ('FINISHED', 'Game finished')], default='WAITING', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='last_answer_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='last_answer_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='streak',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GameMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message_type', models.CharField(choices=[('CHAT', 'Chat message'), ('JOIN', 'Player joined'), ('LEAVE', 'Player left'), ('ANSWER', 'Answer submitted'), ('SYSTEM', 'System message')], default='CHAT', max_length=20)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='base.gamesession')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.player')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
